import keyMirror from 'key-mirror';
export default keyMirror({
  CREATE_ORGANIZATION_FAILURE: null,
  CREATE_ORGANIZATION_REQUEST: null,
  CREATE_ORGANIZATION_SUCCESS: null,
  FETCH_ORGANIZATION_FAILURE: null,
  FETCH_ORGANIZATION_LIST_FAILURE: null,
  FETCH_ORGANIZATION_LIST_REQUEST: null,
  FETCH_ORGANIZATION_LIST_SUCCESS: null,
  FETCH_ORGANIZATION_REQUEST: null,
  FETCH_ORGANIZATION_SUCCESS: null
});
