version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: npm start
    ports:
      - "3000:3000"
    env_file: .env
    restart: always
    volumes:
      - ./:/idea-paas-app
