
const EmailTemplateConstants = {
  CREATE_OR_UPDATE_EMAIL_TEMPLATE: 'CREATE_OR_UPDATE_EMAIL_TEMPLATE',
  CREATE_OR_UPDATE_EMAIL_TEMPLATE_FAIL: 'CREATE_OR_UPDATE_EMAIL_TEMPLATE_FAIL',
  CREATE_OR_UPDATE_EMAIL_TEMPLATE_SUCCESS: 'CREATE_OR_UPDATE_EMAIL_TEMPLATE_SUCCESS',
  GET_ALL_EMAIL_TEMPLATES: 'GET_ALL_EMAIL_TEMPLATES',
  GET_ALL_EMAIL_TEMPLATES_FAIL: 'GET_ALL_EMAIL_TEMPLATES_FAIL',
  GET_ALL_EMAIL_TEMPLATES_SUCCESS: 'GET_ALL_EMAIL_TEMPLATES_SUCCESS',
  GET_EMAIL_TEMPLATE: 'GET_EMAIL_TEMPLATE',
  GET_EMAIL_TEMPLATE_FAIL: 'GET_EMAIL_TEMPLATE_FAIL',
  GET_EMAIL_TEMPLATE_SUCCESS: 'GET_EMAIL_TEMPLATE_SUCCESS',
  RESET_INITIAL_STATE: 'RESET_INITIAL_STATE'
};

export default EmailTemplateConstants;
