import keyMirror from 'key-mirror';
export default keyMirror({
  ADD_FORM_SCHEMA: null,
  CREATE_FORM_SCHEMA_FAILURE: null,
  CREATE_FORM_SCHEMA_REQUEST: null,
  CREATE_FORM_SCHEMA_SUCCESS: null,
  FETCH_FORM_SCHEMA_FAILURE: null,
  FETCH_FORM_SCHEMA_LIST: null,
  FETCH_FORM_SCHEMA_LIST_FAILURE: null,
  FETCH_FORM_SCHEMA_LIST_SUCCESS: null,
  FETCH_FORM_SCHEMA_REQUEST: null,
  FETCH_FORM_SCHEMA_SUCCESS: null,
  FETCH_TEMPLATE_LIST: null,
  FETCH_TEMPLATE_LIST_FAILURE: null,
  FETCH_TEMPLATE_LIST_SUCCESS: null,
  UPDATE_FORM_SCHEMA_STATE: null
});
