import keyMirror from 'key-mirror';
export default keyMirror({
  CREATE_FORM_SCHEMA_FAILURE: null,
  CREATE_FORM_SCHEMA_REQUEST: null,
  CREATE_FORM_SCHEMA_SUCCESS: null,
  FETCH_FORM_SCHEMA_FAILURE: null,
  FETCH_FORM_SCHEMA_LIST: null,
  FETCH_FORM_SCHEMA_LIST_FAILURE: null,
  FETCH_FORM_SCHEMA_LIST_SUCCESS: null,
  FETCH_FORM_SCHEMA_REQUEST: null,
  FETCH_FORM_SCHEMA_SUCCESS: null
});
