import keyMirror from 'key-mirror';
export default keyMirror({
  CREATE_FORM_FIELD_DATA_FAILURE: null,
  CREATE_FORM_FIELD_DATA_REQUEST: null,
  CREATE_FORM_FIELD_DATA_SUCCESS: null,
  FETCH_FORM_FIELD_DATA_FAILURE: null,
  FETCH_FORM_FIELD_DATA_LIST_FAILURE: null,
  FETCH_FORM_FIELD_DATA_LIST_SUCCESS: null,
  FETCH_FORM_FIELD_DATA_REQUEST: null,
  FETCH_FORM_FIELD_DATA_SUCCESS: null
});
