import keyMirror from 'key-mirror';
export default keyMirror({
  CREATE_ROLE_PERMISSION_FAILURE: null,
  CREATE_ROLE_PERMISSION_REQUEST: null,
  CREATE_ROLE_PERMISSION_SUCCESS: null,
  FETCH_ROLE_PERMISSION_FAILURE: null,
  FETCH_ROLE_PERMISSION_REQUEST: null,
  FETCH_ROLE_PERMISSION_SUCCESS: null
});
