import keyMirror from 'key-mirror';
export default keyMirror({
  FETCH_FORM_TRIGGER_FAILURE: null,
  FETCH_FORM_TRIGGER_LIST_FAILURE: null,
  FETCH_FORM_TRIGGER_LIST_REQUEST: null,
  FETCH_FORM_TRIGGER_LIST_SUCCESS: null,
  FETCH_FORM_TRIGGER_REQUEST: null,
  FETCH_FORM_TRIGGER_SUCCESS: null,
  SAVE_FORM_TRIGGER_FAILURE: null,
  SAVE_FORM_TRIGGER_REQUEST: null,
  SAVE_FORM_TRIGGER_SUCCESS: null,
  UPDATE_FORM_TRIGGER_STATE: null
});
